FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY frontend/package.json frontend/package.json
COPY backend/package.json backend/package.json

RUN npm ci

COPY frontend ./frontend

WORKDIR /app/frontend

EXPOSE 5180

CMD ["npx", "vite", "--host"]
